# Generated by Django 2.2.7 on 2019-12-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MhqEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=200)),
                ('lan', models.CharField(max_length=200)),
                ('ui_type', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MhqEmpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('edate', models.DateTimeField(verbose_name='entry date')),
                ('udate', models.DateTimeField(verbose_name='update date')),
                ('wdate', models.DateTimeField(verbose_name='work date')),
                ('names', models.CharField(max_length=200)),
                ('attendance', models.CharField(max_length=200)),
                ('work', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MhqEmpFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('ttype', models.CharField(max_length=200)),
            ],
        ),
    ]
