# Generated by Django 2.2.7 on 2019-12-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='ttype',
            new_name='type',
        ),
    ]
