# Generated by Django 2.2.7 on 2020-01-02 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20191229_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhqempfeedback',
            name='edate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='entry date'),
            preserve_default=False,
        ),
    ]
