# Generated by Django 2.2.7 on 2020-01-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_mhqempfeedback_edate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mhqempfeedback',
            name='touser',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
